import type { Department, Question } from './types'

// Demo department
export const demoDepartment: Department = {
  id: 'cardiology-sheba',
  name: 'מחלקת קרדיולוגיה - שיבא תל השומר',
  nameEn: 'Cardiology Department - Sheba',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

// Demo questions
export const demoQuestions: Question[] = [
  {
    id: 'q1',
    departmentId: 'cardiology-sheba',
    questionText: 'איך היית מדרג/ת את החוויה הכללית שלך במחלקה?',
    questionType: 'emoji',
    options: [
      { value: '1', label: 'גרוע מאוד', emoji: '😡' },
      { value: '2', label: 'לא טוב', emoji: '😟' },
      { value: '3', label: 'בסדר', emoji: '😐' },
      { value: '4', label: 'טוב', emoji: '😊' },
      { value: '5', label: 'מעולה', emoji: '😍' },
    ],
    isRequired: true,
    isDefault: true,
    displayOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q2',
    departmentId: 'cardiology-sheba',
    questionText: 'האם הצוות הרפואי התייחס אליך בכבוד ובאדיבות?',
    questionType: 'emoji',
    options: [
      { value: '1', label: 'בכלל לא', emoji: '😡' },
      { value: '2', label: 'מעט', emoji: '😟' },
      { value: '3', label: 'במידה בינונית', emoji: '😐' },
      { value: '4', label: 'במידה רבה', emoji: '😊' },
      { value: '5', label: 'במידה רבה מאוד', emoji: '😍' },
    ],
    isRequired: true,
    isDefault: true,
    displayOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q3',
    departmentId: 'cardiology-sheba',
    questionText: 'האם קיבלת הסברים מספקים על הטיפול והתרופות?',
    questionType: 'choice',
    options: [
      { value: 'yes', label: 'כן, קיבלתי הסברים מלאים' },
      { value: 'partial', label: 'קיבלתי הסברים חלקיים' },
      { value: 'no', label: 'לא קיבלתי הסברים' },
      { value: 'na', label: 'לא רלוונטי' },
    ],
    isRequired: true,
    isDefault: true,
    displayOrder: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q4',
    departmentId: 'cardiology-sheba',
    questionText: 'אילו שירותים היו לשביעות רצונך המלאה?',
    questionType: 'multi_choice',
    options: [
      { value: 'cleanliness', label: 'ניקיון', emoji: '🧹' },
      { value: 'food', label: 'אוכל', emoji: '🍽️' },
      { value: 'waiting_time', label: 'זמן המתנה', emoji: '⏰' },
      { value: 'staff', label: 'יחס הצוות', emoji: '👨‍⚕️' },
      { value: 'information', label: 'מידע והסברים', emoji: '📋' },
    ],
    isRequired: false,
    isDefault: true,
    displayOrder: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q5',
    departmentId: 'cardiology-sheba',
    questionText: 'כמה כוכבים היית נותן/ת למחלקה?',
    questionType: 'stars',
    isRequired: true,
    isDefault: true,
    displayOrder: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q6',
    departmentId: 'cardiology-sheba',
    questionText: 'יש לך הערות או הצעות לשיפור?',
    questionType: 'open_text',
    isRequired: false,
    isDefault: true,
    displayOrder: 6,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Demo statistics data
export const demoStats = {
  totalResponses: 247,
  completionRate: 89,
  averageRating: 4.2,
  responsesByDay: [
    { date: '2024-01-08', count: 32 },
    { date: '2024-01-09', count: 28 },
    { date: '2024-01-10', count: 45 },
    { date: '2024-01-11', count: 38 },
    { date: '2024-01-12', count: 42 },
    { date: '2024-01-13', count: 35 },
    { date: '2024-01-14', count: 27 },
  ],
  questionStats: [
    {
      questionId: 'q1',
      questionText: 'איך היית מדרג/ת את החוויה הכללית שלך במחלקה?',
      questionType: 'emoji' as const,
      totalResponses: 247,
      distribution: [
        { value: '1', count: 5, percentage: 2 },
        { value: '2', count: 12, percentage: 5 },
        { value: '3', count: 37, percentage: 15 },
        { value: '4', count: 99, percentage: 40 },
        { value: '5', count: 94, percentage: 38 },
      ],
      averageScore: 4.1,
    },
    {
      questionId: 'q5',
      questionText: 'כמה כוכבים היית נותן/ת למחלקה?',
      questionType: 'stars' as const,
      totalResponses: 247,
      distribution: [
        { value: '1', count: 3, percentage: 1 },
        { value: '2', count: 8, percentage: 3 },
        { value: '3', count: 32, percentage: 13 },
        { value: '4', count: 86, percentage: 35 },
        { value: '5', count: 118, percentage: 48 },
      ],
      averageScore: 4.2,
    },
  ],
}
